CREATE TABLE IF NOT EXISTS `zt_taizhang` (
  `id`              int(11)        NOT NULL AUTO_INCREMENT,
  `projectID`       int(11)        NOT NULL DEFAULT 0          COMMENT '关联禅道项目ID，0表示未关联',
  `shortName`       varchar(100)   NOT NULL DEFAULT ''         COMMENT '项目简称',
  `phase`           varchar(30)    NOT NULL DEFAULT ''         COMMENT '项目阶段',
  `projectCategory` varchar(20)    NOT NULL DEFAULT ''         COMMENT '项目类别(施工类/软件类/集成类)',
  `rdManager`       varchar(30)    NOT NULL DEFAULT ''         COMMENT '研发经理账号',
  `currentStatus`   text                                       COMMENT '当前项目情况',
  `projectIntro`    text                                       COMMENT '项目简介',
  `contractSignDate` date         DEFAULT NULL                COMMENT '合同签署时间',
  `subcontractStatus` varchar(50) NOT NULL DEFAULT ''          COMMENT '分包合同状态',
  `engineeringStatus` varchar(50) NOT NULL DEFAULT ''          COMMENT '工程状态',
  `procurementMethod` varchar(50) NOT NULL DEFAULT ''          COMMENT '采购方式',
  `supplyUnit`      varchar(100)   NOT NULL DEFAULT ''         COMMENT '供货单位',
  `constructionUnit` varchar(100) NOT NULL DEFAULT ''          COMMENT '安装/施工单位',
  `planStartDate`   date           DEFAULT NULL                COMMENT '计划开工日期',
  `actualStartDate` date           DEFAULT NULL                COMMENT '实际开工日期',
  `planEndDate`     date           DEFAULT NULL                COMMENT '计划完工日期',
  `actualEndDate`   date           DEFAULT NULL                COMMENT '实际完工日期',
  `acceptanceStatus` varchar(50)  NOT NULL DEFAULT ''          COMMENT '验收情况',
  `securityMeasures` varchar(10)  NOT NULL DEFAULT ''          COMMENT '安保措施是否到位(是/否)',
  `hazardousWork`   varchar(10)    NOT NULL DEFAULT ''         COMMENT '是否涉及危险作业(是/否)',
  `startDocsComplete` varchar(10) NOT NULL DEFAULT ''          COMMENT '开工资料是否齐全(是/否)',
  `initEstHours`    decimal(10,2)  NOT NULL DEFAULT '0.00'     COMMENT '初始预估人天',
  `initBudget`      decimal(10,2)  NOT NULL DEFAULT '0.00'     COMMENT '初始预估成本(万元)',
  `investedHours`   decimal(10,2)  NOT NULL DEFAULT '0.00'     COMMENT '已投入人天',
  `investedCost`    decimal(10,2)  NOT NULL DEFAULT '0.00'     COMMENT '已投入成本(除外购和税)(万元)',
  `currentEstHours` decimal(10,2)  NOT NULL DEFAULT '0.00'     COMMENT '当前预估人天',
  `currentBudget`   decimal(10,2)  NOT NULL DEFAULT '0.00'     COMMENT '当前预估成本(万元)',
  `revenue`         decimal(10,2)  NOT NULL DEFAULT '0.00'     COMMENT '合同金额/收入(万元)',
  `outsourcingAmount` decimal(10,2) NOT NULL DEFAULT '0.00'    COMMENT '外采金额(万元)',
  `receivedAmount` decimal(10,2)   NOT NULL DEFAULT '0.00'     COMMENT '回款金额(万元)',
  `progressDeviation` text                                    COMMENT '进度偏差说明',
  `remark`          text                                       COMMENT '备注',
  `recentMembers`   varchar(500)   NOT NULL DEFAULT ''         COMMENT '近期项目成员(逗号分隔的真实姓名)',
  `sortOrder`       int(11)        NOT NULL DEFAULT 0          COMMENT '显示顺序',
  `deleted`         tinyint(1)     NOT NULL DEFAULT 0,
  `createdAt`       datetime       DEFAULT NULL,
  `updatedAt`       datetime       DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_projectID` (`projectID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目台账';
